apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../cqdg-orchestrations/keycloak-v11
  - ingress.yml

patchesStrategicMerge:
  - clin-theme.yml
  - jars.yml

configMapGenerator:
  - name: jars-list
    options:
      disableNameSuffixHash: true
    files:
      - jars_list.json