apiVersion: v1
kind: Service
metadata:
  labels:
    name: hive-metastore
  name: hive-metastore
spec:
  ports:
  - port: 9083
    protocol: TCP
    targetPort: 9083
  selector:
    name: hive-metastore