---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airflow
configMapGenerator:
    #The following variable needs to be defined in a secret called airflow-db-connection:
    #AIRFLOW__CORE__SQL_ALCHEMY_CONN
    #The following variable needs to be defined in a secret called airflow-fernet-key:
    #AIRFLOW__CORE__FERNET_KEY
    #Also, the following value needs to be defined separately in the environment variables
    #of each impacted pod so that the worker pods don't have to try override the value in
    #the configmap:
    #AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
  - name: airflow-config-core
    options:
      disableNameSuffixHash: true
    envs: 
      - config-core.env
  - name: airflow-config-secrets
    options:
      disableNameSuffixHash: true
    literals:
      #https://airflow.apache.org/docs/apache-airflow/stable/howto/use-alternative-secrets-backend.html#local-filesystem-secrets-backend
      #For this to work, you need to create a secret called airflow-secrets containing the following keys:
      #var.json
      #conn.json
      - AIRFLOW__SECRETS__BACKEND=airflow.secrets.local_filesystem.LocalFilesystemBackend
      - |
        AIRFLOW__SECRETS__BACKEND_KWARGS={"variables_file_path": "/opt/airflow/secrets/var.json", "connections_file_path": "/opt/airflow/secrets/conn.json"}
  - name: airflow-config-cli
    options:
      disableNameSuffixHash: true
    literals:
      - AIRFLOW__CLI__API_CLIENT=airflow.api.client.local_client
  - name: airflow-config-api
    options:
      disableNameSuffixHash: true
    literals:
      - AIRFLOW__API__BACKEND=airflow.api.auth.backend.deny_all
    #The following variable needs to be defined in a secret called airflow-webserver-flask-key:
    #AIRFLOW__WEBSERVER__SECRET_KEY
  - name: airflow-config-operators
    options:
      disableNameSuffixHash: true
    literals:
      - AIRFLOW__OPERATORS__DEFAULT_OWNER=airflow
      - AIRFLOW__OPERATORS__DEFAULT_CPUS=1
      - AIRFLOW__OPERATORS__DEFAULT_RAM=512
      - AIRFLOW__OPERATORS__DEFAULT_DISK=512
      - AIRFLOW__OPERATORS__DEFAULT_GPUS=0
  - name: airflow-config-webserver
    options:
      disableNameSuffixHash: true
    envs:
      - config-webserver.env
    #Note that the following smtp values need to be configured in a secret named airflow-smtp:
    #AIRFLOW__SMTP__SMTP_HOST
    #AIRFLOW__SMTP__SMTP_STARTTLS
    #AIRFLOW__SMTP__SMTP_SSL
    #AIRFLOW__SMTP__SMTP_USER
    #AIRFLOW__SMTP__SMTP_PASSWORD
    #AIRFLOW__SMTP__SMTP_PORT
    #AIRFLOW__SMTP__SMTP_MAIL_FROM
  - name: airflow-config-email
    options:
      disableNameSuffixHash: true
    literals:
      - AIRFLOW__EMAIL__EMAIL_BACKEND=airflow.utils.email.send_email_smtp
  - name: airflow-config-scheduler
    options:
      disableNameSuffixHash: true
    envs:
      - config-scheduler.env
  - name: airflow-config-kubernetes
    options:
      disableNameSuffixHash: true
    envs:
      - config-kubernetes.env
  - name: airflow-config-kubernetes-template
    options:
      disableNameSuffixHash: true
    files:
      - airflow_template.yml