apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  template:
    spec:
      containers:
        - name: keycloak
          env:
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: username
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-credentials
                  key: password
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: keycloak-db
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: keycloak
            #By default, assume that keycloak will be behind a
            #reverse-proxy which is the prod-friendly setting
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"