---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: keycloak-jars
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: keycloak-build-artifacts
              configMap:
                name: keycloak-build-artifacts
                defaultMode: 0444
            - name: repo
              emptyDir: {}
          restartPolicy: Never
          initContainers:
            - name: plan
              image: ferlabcrsj/binary-artifacts:95e17adec8858b1919c0547104a45b86d0a600fc
              imagePullPolicy: IfNotPresent
              command: ["python", "/opt/scripts/plan.py"]
              volumeMounts:
                - name: keycloak-build-artifacts
                  mountPath: /opt/build_list
                  readOnly: true
                - name: repo
                  mountPath: /opt/repo
              envFrom:
                - secretRef:
                    name: s3-credentials
              env:
                - name: GIT_REPO
                  value: __UNDEFINED__
                - name: GIT_BRANCH
                  value: __UNDEFINED__
                - name: S3_ENDPOINT
                  value: __UNDEFINED__
                - name: S3_REGION
                  value: __UNDEFINED__
            - name: build
              image: openjdk:11.0-buster
              imagePullPolicy: IfNotPresent
              command: ["/opt/repo/RUN_BUILD.sh"]
              volumeMounts:
                - name: repo
                  mountPath: /opt/repo
          containers:
            - name: push
              image: ferlabcrsj/binary-artifacts:95e17adec8858b1919c0547104a45b86d0a600fc
              imagePullPolicy: IfNotPresent
              command: ["python", "/opt/scripts/push.py"]
              volumeMounts:
                - name: keycloak-build-artifacts
                  mountPath: /opt/build_list
                  readOnly: true
                - name: repo
                  mountPath: /opt/repo
              envFrom:
                - secretRef:
                    name: s3-credentials
              env:
                - name: S3_ENDPOINT
                  value: __UNDEFINED__
                - name: S3_REGION
                  value: __UNDEFINED__
            - name: prune
              image: ferlabcrsj/binary-artifacts:95e17adec8858b1919c0547104a45b86d0a600fc
              imagePullPolicy: IfNotPresent
              command: ["python", "/opt/scripts/prune.py"]
              volumeMounts:
                - name: keycloak-build-artifacts
                  mountPath: /opt/build_list
                  readOnly: true
              envFrom:
                - secretRef:
                    name: s3-credentials
              env:
                - name: S3_ENDPOINT
                  value: __UNDEFINED__
                - name: S3_REGION
                  value: __UNDEFINED__