---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airflow
configMapGenerator:
  - name: airflow-scripts
    options:
      disableNameSuffixHash: true
    files:
      - airflow-init.py
      - manage-users.py