---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow
  labels:
    app: airflow-webserver
spec:
  type: ClusterIP
  selector:
    app: airflow-webserver
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080