---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-ceph
  namespace: spark
  labels:
    name: spark
data:
  spark-ceph.conf: |
    spark.app.name=spark-ceph
    spark.executor.instances=5
    spark.kubernetes.container.image=ferlabcrsj/spark:ba3d4e6d97baef31fb450cb6c75c73b19ec64fce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-ceph-endpoint
  namespace: spark
  labels:
    name: spark
data:
  spark-ceph-endpoint.conf: |
    spark.hadoop.fs.s3a.endpoint=__UNDEFINED__