apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aidbox
  name: aidbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aidbox
  template:
    metadata:
      labels:
        app: aidbox
    spec:
      containers:
      - image: healthsamurai/devbox:0.4.8
        name: devbox
        resources:
          requests:
            memory: "1024Mi"
            cpu: '1.00'
          limits:
            memory: "1024Mi"
            cpu: '2.00'
        command:
          - "/bin/sh"
          - "-c"
          - "java -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -XX:-OmitStackTraceInFastThrow   -Dcom.sun.management.jmxremote   -Dcom.sun.management.jmxremote.host=127.0.0.1   -Djava.rmi.server.hostname=127.0.0.1   -Dcom.sun.management.jmxremote.port=9099   -Dcom.sun.management.jmxremote.authenticate=false   -Dcom.sun.management.jmxremote.ssl=false   -jar /aidbox.jar -m devbox.core"
        env:
          - name: AIDBOX_FHIR_VERSION
            value: "4.0.0"
          - name: PGHOST
            value: aidbox-db
          - name: PGPORT
            value: "5432"
          - name: PGDATABASE
            value: devbox
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: aidbox-db-credentials
                key: username
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: aidbox-db-credentials
                key: password
          - name: AIDBOX_LICENSE_ID
            valueFrom:
              secretKeyRef:
                name: aidbox-license
                key: license_id
          - name: AIDBOX_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: aidbox-license
                key: license_key
          - name: AIDBOX_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: aidbox-credentials
                key: client_id
          - name: AIDBOX_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: aidbox-credentials
                key: client_secret
          - name: AIDBOX_ADMIN_ID
            valueFrom:
              secretKeyRef:
                name: aidbox-credentials
                key: admin_id
          - name: AIDBOX_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aidbox-credentials
                key: admin_password