---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-pi
  namespace: spark
  labels:
    name: spark
data:
  spark-pi.conf: |
    spark.app.name=spark-pi
    spark.executor.instances=5
    spark.kubernetes.container.image=ferlabcrsj/spark:ba3d4e6d97baef31fb450cb6c75c73b19ec64fce
